### ISSUE TITLE
Synthetic event handlers, passing event

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/stage0#15]
Hi, so sorry, it's me again.  Probably something I am missing clearly but doesn't the `eventHandler` below need to be passed the actual event?   If not, how does it get a reference to it?

```
   let dom = event.target;
    while (dom !== null) {
      const eventHandler = dom[eventKey];
      if (eventHandler) {
        eventHandler();
        return;
      }
....
```

**Comment by tomcon** [comment]
@mrjjwright  Think there was a similar situation with the associated project domc, see here:
https://github.com/Freak613/domc/pull/2/commits/cba1c86c83d2acd56d01cb1b1e28b8266eda067f

**Comment by mrjjwright** [comment]
Thanks Tom!

**Comment by Freak613** [comment]
Yes, I missed that one.
Fixed.
