### ISSUE TITLE
TypeScript declaration file

### ISSUE THREAD

**Issue by liamcurry** [Freak613/stage0#19]
TypeScript declarations would be nice. This could be implemented as an `index.d.ts` file. More info: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by Freak613** [comment]
I'll try to do it later. 
Not sure I can validate it properly, as I'm not working with TS much.

Since this library has a bunch of files, would it be enough to have `<name>.d.ts` per each of them?

**Comment by Freak613** [comment]
Added in https://github.com/Freak613/stage0/pull/24
