### ISSUE TITLE
[Q] How do we add conditional HTML or stage0 components?

### ISSUE THREAD

**Issue by trsh** [Freak613/stage0#2]
Could not find any examples.

**Comment by trsh** [comment]
Im delusing something like this:

const htmlView = h`#html`;
  const inputView = h`<div class="input-title">#inputName</div>`;

  function InputTitle(_item, scope) {
    const htmlW = htmlView;
    const inputW = htmlView;

    const { html } = htmlView.collect(htmlW);
    const { inputName } = inputView.collect(inputW);

    inputName.nodeValue = scope.input.name;
    html.nodeValue = scope.showControl() ? inputW : ``;

    let a = scope.input.name,
      a2,
      b = scope.showControl(),
      b2;

    html.update = function(scope) {
      a2 = scope.input.name;
      b2 = scope.showControl();

      if (b2 && a2 !== a) {
        a = inputName.nodeValue = a2;
      }
      if (b2 !== b) {
        b = b2;
        html.nodeValue = b ? inputW : ``;
      }
    };

    return root;
  }

**Comment by Freak613** [comment]
Since we're working with native DOM nodes, conditional would be something like that:
```javascript
let a, a2
function update(cond) {
    a2 = cond
    if (a2 !== a) {
        if (cond) {
            container.appendChild(node)
        } else {
            container.removeChild(node)
        }
    }
}
```

**Comment by Freak613** [comment]
This library requires good DOM API knowledge.
`nodeValue` is property of Node allowing to set text content of the node. 
For insertion we need to use proper DOM methods of Node.
https://developer.mozilla.org/en-US/docs/Web/API/Node

**Comment by Freak613** [comment]
I might require first get some experience building UI using plain old VanillaJS.
This library is just set of helpers for that way.
Check out: http://youmightnotneedjquery.com , it has good set of most useful DOM methods.

**Comment by trsh** [comment]
@Freak613 ok got it. I have good exp with Vanilla JS, just didn't grasp the concept fully yet of this lib. But its clear now :)
