### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Yakulu** [Freak613/stage0#21]
Hi,

Thanks for this wonderful piece of work. I do not see any LICENSE file nor license indication on the repository nor into the files. I've only found MIT note on `package.json`. To me, without license, we are in classical copyright and nobody really can fork your library or contribute to it (only exception : personal usage could be achieved).

You may want to add a LICENSE file to clarify the situation ? Thank you in advance for your answer.

**Comment by Freak613** [comment]
Missed it somehow. Updated repo with MIT licence file.
