### ISSUE TITLE
reconcile fast path create DocumentFragment

### ISSUE THREAD

**Issue by luwes** [Freak613/stage0#23]
Would using a temporary DocumentFragment be an easy performance increase for the fast path create if the number of items is high enough?

Or is there a reason not to do this?

**Comment by leeoniya** [comment]
in simple detached-dom cases it's actually worse for perf, but in more complex cases it's better. the trick is probably getting the heuristics right to know when it's worth using?

https://stackoverflow.com/questions/14203196/does-using-a-document-fragment-really-improve-performance/35242602#35242602

**Comment by luwes** [comment]
thanks @leeoniya, I did a performance test in Chrome dev tools and like you said it was worse performance. didn't expect that but good to know.

**Comment by Freak613** [comment]
I made hundreds of tests and concluded that DocumentFragment doesn't provide significant performance boost, even making it slower.
So yes, maybe somewhere it can benefit, but in common doesn't worth it.
