### ISSUE TITLE
Missing keyed

### ISSUE THREAD

**Issue by mrjjwright** [Freak613/stage0#5]
Love this lib, pairs awesome with S.js.  I am not getting `keyed.js` when I do a `yarn add stage0`.   Any ideas?

![screen shot 2018-11-18 at 9 48 59 pm](https://user-images.githubusercontent.com/4343/48686897-cd241980-eb7b-11e8-8e67-c8ef20e3e108.png)

**Comment by Freak613** [comment]
Is it latest version?
I just checked and everything is there.
yarn could cache some old version, you should try to update stage0 to the latest one
https://yarnpkg.com/lang/en/docs/cli/upgrade/

**Comment by mrjjwright** [comment]
Holy cow, for some reason I was working on a really old version of stage0 `0.0.2`!   Didn't check my package.json before submitting this.   This, not sure how that happened.  Again, thanks for the awesome lib!

**Comment by Freak613** [comment]
You're welcome)
