### ISSUE TITLE
[FR] add option for array element comparison

### ISSUE THREAD

**Issue by trsh** [Freak613/stage0#6]
```
reconcile(
    parent,
    renderedValues,
    newValues,
    (a, b) => {
      return a.id === b.id
    }
    ....
)
```

Otherwise it's impossible for the script to figure out when two objects should be considered as same or not. And looking at the code:

```
a = renderedValues[prevStart], b = data[newStart]
        while(a === b) {
```

I believe this works only with Values (strings, numbers) and objects that share same memory, what is uncommon. Maybe im wrong.

**Comment by Freak613** [comment]
Have you tried [keyed](https://github.com/Freak613/stage0#keyed) helper?
It's reconciler for keyed collections.

**Comment by trsh** [comment]
I see. But what if I have complex conditions? Like key deep in object or multiple conditions?

**Comment by trsh** [comment]
But keyed solved my case, so I'm closing this.
