### ISSUE TITLE
Support for fragments?

### ISSUE THREAD

**Issue by LeslieJohnson** [Freak613/stage0#7]
In `examples/todomvc/app.js` the second footer with class='info' doesn't exist in the DOM. Chrome dev tools don't show anything there at all.

**Comment by Freak613** [comment]
Oops, yeah, you're right.
That's because stage0 doesn't support fragments for now (2 or more root nodes in a template).
I will update example to remove it.

**Comment by LeslieJohnson** [comment]
Perfectly reasonable to accept only one root node. Surplus and others are the same way. I'll adjust. :)
